server:
  port: 8081

spring:
  application:
    name: notification-service
  cloud:
    service-registry:
      auto-registration:
        enabled: true
    discovery:
      enabled: true
    config:
      enabled: false
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: notification-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "ru.oleg520.dto"

eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true

app:
  kafka:
    topics:
      user-events: user-events
    consumer:
      group-id: notification-group
  
  email:
    templates:
      create:
        subject: "Добро пожаловать!"
        message: "Ваш аккаунт был успешно создан. Добро пожаловать в нашу систему!"
      delete:
        subject: "Аккаунт удален"
        message: "Ваш аккаунт был удален из системы. Спасибо за использование наших услуг!"
